# Generated by Django 5.0.6 on 2024-05-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_customs_acnt_no_alter_customs_adhar_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customs',
            old_name='age',
            new_name='account_no',
        ),
    ]
